In [1]:
import pandas as pd
import numpy as np

In [ ]:
file_path = r"C:\Users\MTC\Desktop\RetailPulse\data\raw\online_retail_II.xlsx"
df = pd.read_excel(file_path, sheet_name="Year 2010-2011")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df_clean = df.copy()

In [4]:
df_clean.duplicated().sum()

np.int64(5268)

In [5]:
df_clean[df_clean.duplicated()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [6]:
print(df_clean.shape)
df.shape

(541910, 8)

(541910, 8)

In [7]:
df_clean[df_clean.duplicated(keep=False)].sort_values(
    ["Invoice", "StockCode"]
).head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [8]:
exact_duplicates = df_clean.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

Exact duplicate rows: 5268

In [9]:
df_clean = df_clean.drop_duplicates()

### Removed 5268 identical duplicates

In [10]:
df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:", len(df_clean))
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Rows after removing duplicates: 536642
Remaining exact duplicates: 0

In [11]:
# Finding the number of missing customer IDs
missing_customer = df_clean[df_clean["Customer ID"].isna()]
print("Number of rows with missing Customer ID:", len(missing_customer))

Number of rows with missing Customer ID: 135037

In [12]:
missing_customer.shape

(135037, 8)

In [13]:
missing_customer.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom

In [14]:
df_clean["Customer ID"].isna().value_counts()

Customer ID
False    401605
True     135037
Name: count, dtype: int64

In [15]:
# Data type of the customer ID is currently float, lets convert it to integer type.
df_clean["Customer ID"] = df_clean["Customer ID"].astype("Int64")

In [16]:
df_clean["Customer ID"].dtype

Int64Dtype()

In [17]:
df_clean["Customer ID"].isna().sum()

np.int64(135037)

In [18]:
# Handling missing descriptions
missing_description = df_clean[df_clean["Description"].isna()]

In [19]:
missing_description[[
    "StockCode",
    "Description",
    "Quantity",
    "Price",
    "Customer ID",
    "Country"
]].head(20)

     StockCode Description  Quantity  Price  Customer ID         Country
622      22139         NaN        56    0.0         <NA>  United Kingdom
1510     21134         NaN         1    0.0         <NA>  United Kingdom
1985     37509         NaN         1    0.0         <NA>  United Kingdom
1986     22145         NaN         1    0.0         <NA>  United Kingdom
2022     20950         NaN         1    0.0         <NA>  United Kingdom
2023    85226A         NaN         1    0.0         <NA>  United Kingdom
2024     85044         NaN         1    0.0         <NA>  United Kingdom
2025     37461         NaN         3    0.0         <NA>  United Kingdom
2026     84670         NaN        23    0.0         <NA>  United Kingdom
2406     21777         NaN       -10    0.0         <NA>  United Kingdom
4347    84952C         NaN       -38    0.0         <NA>  United Kingdom
4348    84952C         NaN        19    0.0         <NA>  United Kingdom
7187     35951         NaN        57    0.0         <NA>  United Kingdom
7188     22712         NaN       -20    0.0         <NA>  United Kingdom
7189     22028         NaN       -20    0.0         <NA>  United Kingdom
7190     85067         NaN        -6    0.0         <NA>  United Kingdom
7191     21421         NaN       110    0.0         <NA>  United Kingdom
7192     21414         NaN       -22    0.0         <NA>  United Kingdom
7193     21653         NaN        -6    0.0         <NA>  United Kingdom
7194     21651         NaN        70    0.0         <NA>  United Kingdom

In [20]:
'''Tells how many unique descriptions are associated with each stock code. If a stock code has multiple descriptions
 it may indicate inconsistent data entry or product variations.'''

description_per_stock = (
    df_clean
    .dropna(subset=["Description"])
    .groupby("StockCode")["Description"]
    .nunique()
)

In [21]:
description_per_stock.head()

StockCode
10002    1
10080    2
10120    1
10125    1
10133    2
Name: Description, dtype: int64

In [22]:
multi_description = description_per_stock[description_per_stock > 1]

print("StockCodes with multiple descriptions:", len(multi_description))

StockCodes with multiple descriptions: 650

In [23]:
multi_description.sort_values(ascending=False).head(10)

StockCode
20713     8
23084     7
21830     6
85175     6
23131     5
21181     5
23343     5
85172     5
72807A    5
22812     4
Name: Description, dtype: int64

In [24]:
df_clean[df_clean["StockCode"] == "20713"][
    ["StockCode", "Description", "Quantity", "Price"]
].drop_duplicates()

Empty DataFrame
Columns: [StockCode, Description, Quantity, Price]
Index: []

In [25]:
df_clean.shape

(536642, 8)

In [26]:
missing_stockcodes = missing_description["StockCode"].unique()

known_stockcodes = df_clean.loc[
    df_clean["Description"].notna(),
    "StockCode"
].unique()

recoverable = missing_description[
    missing_description["StockCode"].isin(known_stockcodes)
]

print("Missing descriptions:", len(missing_description))
print("Potentially recoverable:", len(recoverable))

print(
    "Potentially recoverable %:",
    round(len(recoverable) / len(missing_description) * 100, 2)
)

Missing descriptions: 1454
Potentially recoverable: 1342
Potentially recoverable %: 92.3

In [28]:
unique_description_per_stock = (
    df_clean
    .dropna(subset=["Description"])
    .groupby("StockCode")["Description"]
    .nunique()
)

reliable_stockcodes = unique_description_per_stock[
    unique_description_per_stock == 1
].index

print(
    "StockCodes with exactly one description:",
    len(reliable_stockcodes)
)

StockCodes with exactly one description: 3308

In [29]:
description_mapping = (
    df_clean[
        df_clean["StockCode"].isin(reliable_stockcodes)
        & df_clean["Description"].notna()
    ]
    .drop_duplicates("StockCode")
    .set_index("StockCode")["Description"]
)

In [30]:
df_clean["Description"] = (
    df_clean["Description"]
    .fillna(df_clean["StockCode"].map(description_mapping))
)

In [31]:
print("Remaining missing descriptions:",
      df_clean["Description"].isna().sum())

Remaining missing descriptions: 421

In [32]:
df_clean.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             Int64
Country                object
dtype: object

In [33]:
df_clean["InvoiceDate"] = pd.to_datetime(
    df_clean["InvoiceDate"],
    errors="coerce"
)

In [ ]:
print(df_clean["InvoiceDate"].isna().sum())

# Its 0 so it means the date column is clean and has no missing values.

0

In [36]:
df_clean["IsCancellation"] = (
    df_clean["Invoice"].astype(str).str.startswith("C")
)

df_clean["IsCancellation"].value_counts()

IsCancellation
False    527391
True       9251
Name: count, dtype: int64

In [ ]:
# Creating a new column called revenue (quantity * price)
df_clean["Revenue"] = (
    df_clean["Quantity"] * df_clean["Price"]
)

In [38]:
df_clean[
    ["Quantity", "Price", "Revenue"]
].head()

   Quantity  Price  Revenue
0         6   2.55    15.30
1         6   3.39    20.34
2         8   2.75    22.00
3         6   3.39    20.34
4         6   3.39    20.34

In [ ]:
# Categorizing transactions based on price

df_clean["TransactionType"] = "Normal Sale"

df_clean.loc[
    df_clean["Price"] < 0,
    "TransactionType"
] = "Bad Debt Adjustment"

df_clean.loc[
    df_clean["Price"] == 0,
    "TransactionType"
] = "Zero Price or Adjustment"

df_clean.loc[
    (df_clean["Quantity"] < 0) &
    (df_clean["Price"] > 0),
    "TransactionType"
] = "Return or Cancellation"

In [46]:
df_clean["TransactionType"].value_counts()

TransactionType
Normal Sale                 524879
Return or Cancellation        9251
Zero Price or Adjustment      2510
Bad Debt Adjustment              2
Name: count, dtype: int64

In [48]:
# Creating date features for EDA

df_clean["Year"] = df_clean["InvoiceDate"].dt.year
df_clean["Month"] = df_clean["InvoiceDate"].dt.month
df_clean["Day"] = df_clean["InvoiceDate"].dt.day
df_clean["DayOfWeek"] = df_clean["InvoiceDate"].dt.dayofweek

df_clean["YearMonth"] = (
    df_clean["InvoiceDate"].dt.to_period("M")
)

df_clean["Date"] = (
    df_clean["InvoiceDate"].dt.date
)

In [54]:
print(df_clean.shape)
print()

print(df_clean.isna().sum())
print()

print(df_clean.duplicated().sum())
print()

(536642, 17)

Invoice                 0
StockCode               0
Description           421
Quantity                0
InvoiceDate             0
Price                   0
Customer ID        135037
Country                 0
IsCancellation          0
Revenue                 0
TransactionType         0
Year                    0
Month                   0
Day                     0
DayOfWeek               0
YearMonth               0
Date                    0
dtype: int64

0

In [57]:
# Saving the cleaned data to a new CSV file

df_clean.to_excel(
    r"C:\Users\MTC\Desktop\RetailPulse\data\processed\retail_clean.xlsx",
    index=False
)

### Data is saved now successfully and data cleaning is also done